### PR TITLE
Panic if the pointer is null in into_owned

### PR DESCRIPTION
**Pull request by ghost**
This is a just small quality-of-life improvement. It's better to fail early when converting a null `Ptr` into `Owned` than run into nasty memory issues and potential SIGSEGVs later.

The overhead of testing whether the pointer is null should be really small. The `into_owned` method is typically used to drop the value and deallocate memory, so one quick check is not going to affect performance.

### CODE REVIEW

**Review by Vtec234 — APPROVED** [review]

**Review by jeehoonkang — APPROVED** [review]

**Comment by jeehoonkang** [comment]
How about asserting only in debug mode? `debug_assert!(...)`

Because in implementing #30, I had to use `Owned::from_data` in `compare_and_set`.  It's in a reasonably hot path.  `Owned` should be converted to `usize` for performing CAS, and then converted back to `Owned` when CAS fails.

**Comment by ghost** [comment]
On another thought, shouldn't `into_owned()` return `Option<Owned<T>>` instead of `Owned<T>`?
That might be even more foolproof.

**Comment by Vtec234** [comment]
@stjepang: that would add a cumbersome `unwrap()` in 99% of the uses where the user expects the `Ptr` to be valid and a slightly nicer API for the 1% when the `Ptr` might actually be null, which can just be checked with `is_null`. `debug_assert` might be better though.

**Comment by ghost** [comment]
Fair enough - I've switched to `debug_assert!`. Merging...

**Pull request merged**
